### ISSUE TITLE
下單時，新增「備註」欄位

### ISSUE THREAD

**Issue by brain502** [brain502/Getmii#11]
一、買家需客製化時，在各頁面加入「備註」資訊
二、輸入預設為三列
三、需修改頁面如下
1. 買家端，PC版 & RWD版 (詳見紅色箭頭處)
https://www.getmii.today/order/info?number=880755V000485
![default](https://user-images.githubusercontent.com/32536714/43735034-26d7e8bc-99ec-11e8-9042-a3c9af10f05d.jpg)
![rwd_](https://user-images.githubusercontent.com/32536714/43735202-a586e78a-99ec-11e8-84c8-a4a595e82cb5.jpg)

https://www.getmii.today/orderapi/order_check?MerchantTradeNo=880755V000445
![default](https://user-images.githubusercontent.com/32536714/43735143-7b6147fc-99ec-11e8-9b89-56112e180a22.jpg)
![rwd_](https://user-images.githubusercontent.com/32536714/43735192-9ec565b6-99ec-11e8-8e01-fcb16ee39048.jpg)

https://www.getmii.today/order/order
![default](https://user-images.githubusercontent.com/32536714/43735163-8f2ba750-99ec-11e8-9411-69b4f4dbb169.jpg)
![rwd_](https://user-images.githubusercontent.com/32536714/43735182-96ce6434-99ec-11e8-9500-e03386b6b2cf.jpg)

2. 設計師端
https://www.getmii.today/su_order/order
![_](https://user-images.githubusercontent.com/32536714/43735283-d25f12aa-99ec-11e8-8952-962d82b2a02c.jpg)

@hungmi

**Comment by chagn** [comment]
<img width="1073" alt="2018-08-27 8 59 15" src="https://user-images.githubusercontent.com/4253273/44661100-288eb180-aa3c-11e8-9d29-df2d0b21d103.png">

這邊左右不太好切齊, 看你們有沒有其他想法跟要求是你們可以接受的版本

**Comment by chagn** [comment]
https://github.com/brain502/Getmii/pull/13

@brain502

**Comment by brain502** [comment]
優化 UI for 複數個產品狀態
@chagn 

RWD版本
![rwd_ _](https://user-images.githubusercontent.com/32536714/44742076-8d780380-ab31-11e8-93ba-19d396cd49a6.jpg)


PC版本
![_](https://user-images.githubusercontent.com/32536714/44742102-9ff23d00-ab31-11e8-8ee7-b98bae3b9adb.jpg)

**Comment by chagn** [comment]
<img width="312" alt="2018-08-30 7 57 54" src="https://user-images.githubusercontent.com/4253273/44850631-6f74e500-ac90-11e8-9539-75e626d32030.png">
<img width="1073" alt="2018-08-30 7 58 13" src="https://user-images.githubusercontent.com/4253273/44850633-6f74e500-ac90-11e8-9214-fd7bf53978b3.png">
<img width="1073" alt="2018-08-30 8 03 39" src="https://user-images.githubusercontent.com/4253273/44850634-6f74e500-ac90-11e8-8348-7633eb74232a.png">

**Comment by chagn** [comment]
[電腦版]
<img width="1070" alt="2018-08-30 8 11 59" src="https://user-images.githubusercontent.com/4253273/44851250-43f2fa00-ac92-11e8-9dac-f2b416874732.png">
[手機版]
<img width="314" alt="2018-08-30 8 21 59" src="https://user-images.githubusercontent.com/4253273/44851316-7866b600-ac92-11e8-9a08-f625bba573ad.png">

**Comment by chagn** [comment]
[總管理後台]
<img width="1440" alt="2018-08-30 8 42 08" src="https://user-images.githubusercontent.com/4253273/44852208-3a1ec600-ac95-11e8-8387-15f1333dc751.png">

**Comment by brain502** [comment]
1. 備註欄字串留言功能、新增「返回修改」按紐，驗證初步OK
2. 版面要符合Brain期望，預計下周重寫，follow Vincent 建議
3. 字串超過Vincent設計，要出現 table 警告視窗，Brain 提供圖面 deadline: 9/5
4. 備註填寫完後，到訂單確認頁，買家再回到上一頁，填寫的資料要暫存 => @ahstarchang 再告知修改時間

**Comment by brain502** [comment]
一、區域： 出貨資料、發票匯出
1. 輸入框的長度，請改回舊版
2. 發票匯出的輸入框，目前靠左對齊 => OK，維持Vincent版本
3. 捐出發票的選擇鈕位置 => OK，維持Vincent版本

二、區域： 訂單備註
1. 輸入框的寬度縮小，參考下圖連結
https://user-images.githubusercontent.com/32536714/44742102-9ff23d00-ab31-11e8-8ee7-b98bae3b9adb.jpg
2. 訂單備註上方，遺漏分隔線
https://user-images.githubusercontent.com/32536714/44742102-9ff23d00-ab31-11e8-8ee7-b98bae3b9adb.jpg
3. 輸入框內的說明，文字規格修改，如下連結
https://user-images.githubusercontent.com/32536714/45473090-a0f9b000-b768-11e8-8b18-2d9096e46019.jpg
4. 輸入框，僅能被往下拉長，不可以往右拉大，與往左縮小
5. 字串修改，如果 b 方案是一下子就改好的話，請採用 b 方案： <09.13新增>
      a.「若設計師有提供刻字......注意的地方。」後面加上「請低於150個字。
      b. 或者改為字數提醒器如右 → 0/150；

三、衍生問題
1. 首頁關鍵字輸入框，輸入品牌館名稱，無法被搜尋到
2. 出貨資訊頁輸入後，無法進行按下一步付款

@chagn @ahstarchang

**Comment by chagn** [comment]
一、區域： 出貨資料、發票匯出

- [ ]  輸入框的長度，請改回舊版

發票匯出的輸入框，目前靠左對齊 => OK，維持Vincent版本
捐出發票的選擇鈕位置 => OK，維持Vincent版本
二、區域： 訂單備註

- [ ]  輸入框的寬度縮小，參考下圖連結
https://user-images.githubusercontent.com/32536714/44742102-9ff23d00-ab31-11e8-8ee7-b98bae3b9adb.jpg

- [ ] 訂單備註上方，遺漏分隔線
https://user-images.githubusercontent.com/32536714/44742102-9ff23d00-ab31-11e8-8ee7-b98bae3b9adb.jpg

- [ ] 輸入框內的說明，文字規格修改，如下連結
https://user-images.githubusercontent.com/32536714/45473090-a0f9b000-b768-11e8-8b18-2d9096e46019.jpg
輸入框，僅能被往下拉長，不可以往右拉大，與往左縮小

- [ ] 字串修改，如果
 b 方案是一下子就改好的話，請採用 b 方案： <09.13新增>
a.「若設計師有提供刻字......注意的地方。」後面加上「請低於150個字。
b. 或者改為字數提醒器如右 → 0/150；
三、衍生問題

- [ ] 首頁關鍵字輸入框，輸入品牌館名稱，無法被搜尋到

- [ ] 出貨資訊頁輸入後，無法進行按下一步付款

**Comment by chagn** [comment]
稍微解釋一下
首頁關鍵字輸入框，輸入品牌館名稱，無法被搜尋到
原因是因為測試站的資料庫是使用sqlite3，一些語法與mysql不同，已修改成兩者都可以用的，並非這次修改造成的。

**Comment by brain502** [comment]
@chagn @ahstarchang 
剩 #19, 20, 21, 24
https://docs.google.com/spreadsheets/d/10b1g3KmojEHieTlKnKowr-HiHskaoifFNsnlJaY9igE/edit#gid=1744288827

**Comment by brain502** [comment]
#19,20,21 確認OK  (除#24)
請更新至 www 版

@chagn
