### ISSUE TITLE
品牌館連結修改

### ISSUE THREAD

**Issue by brain502** [brain502/Getmii#20]
品牌館：id=22
目前狀況：https://www.getmii.today/brand/https://www.facebook.com/m.zoo2014
請修改為：https://www.getmii.today/brand/m zoo
                  如果 m 與 z 中間不能有空格，則改為 https://www.getmii.today/brand/mzoo

![mzoo](https://user-images.githubusercontent.com/32536714/46924923-8febd980-d05b-11e8-9274-8c3e9e0fc9cc.jpg)

@chagn

**Comment by chagn** [comment]
@brain502 
只針對這個(id=22)去修改嗎？

**Comment by chagn** [comment]
https://www.getmii.today/brand/m_zoo

**Comment by brain502** [comment]
Checked ok
