### ISSUE TITLE
按上一頁，要記錄首頁滑的位置 

### ISSUE THREAD

**Issue by brain502** [brain502/Getmii#24]
@chagn 
一、問題說明：
商品多，TA點太多層後，按上一頁回到首頁時，會回到最置頂的位置，UX不佳

二、操作修改說明：
首頁商品流 / 文章流→ 點任何   icon → 進去任何一個頁面 → 按返回上一頁一直到回到首頁 → 必須回到一開始的位置          

三、現況
目前只有從首頁點商品圖片，會有紀錄前面的路徑

**Comment by chagn** [comment]
結論：開新分頁。

**Comment by brain502** [comment]
Check OK
@chagn
