### ISSUE TITLE
FB粉絲團再行銷

### ISSUE THREAD

**Issue by brain502** [brain502/Getmii#4]
網站程式協助嵌入 FB 像素
@hungmi 
![fb](https://user-images.githubusercontent.com/32536714/42834589-9892ee7a-8a29-11e8-8094-91984779d4c2.png)

**Comment by brain502** [comment]
[ 像素碼未安裝完整 ]

如下圖，我在Chrome安裝了Facebook pixel helper來檢測像素安裝是否成功，
依照 FB 行銷影音教學，得知有兩個問題
1. 缺少 view content (事件像素碼)，如下圖
![fb _](https://user-images.githubusercontent.com/32536714/43359513-d902fae0-92d5-11e8-90d8-7de6fb9e1450.jpg)


2. Microdata Automatically Detected，應該是綠色勾勾
![fb _](https://user-images.githubusercontent.com/32536714/43359514-df9eb39e-92d5-11e8-9cc8-2b758096f2e0.jpg)

**Comment by hungmi** [comment]
![image](https://user-images.githubusercontent.com/8531846/43362030-cfe4b970-9312-11e8-9136-0983e29d7b4a.png)
我這邊看到的是閃電符號耶

**Comment by brain502** [comment]
1.
我的也是藍色閃電符號
我的意思是，好像要「綠色打勾」
下周二與Facebook會電話會議，我會確認他藍色閃電是否正常

2.
已確認有加入ViewContent => ok

@hungmi
