### ISSUE TITLE
Google header

### ISSUE THREAD

**Issue by brain502** [brain502/Getmii#6]
瀏覽者在Chrome搜詢到 Getmii 後，官網需出現以下紅框描述
建置項目：「官網首頁」 「 設計日誌」
![google header](https://user-images.githubusercontent.com/32536714/42835300-0e5cd566-8a2b-11e8-9f6c-d241822fe86b.png)
@hungmi

**Comment by brain502** [comment]
@chagn 
根據你的回覆，我這邊可以是試著管理下述嗎? 我試著去點，可是一直不知道怎麼玩

新增gem, 方便管理 SEO
https://github.com/kpumuk/meta-tags

可管理範圍包含
title, description, keywords
og:title, og:description, og:keywords

**Comment by chagn** [comment]
我只是告訴你做法，要在後台管理的話要再多開資料庫欄位，目前沒有。

**Comment by brain502** [comment]
1. 目前有看到 鍵入Getmii 的成效
2. 新增gem，與Vincent在討論，先記錄到Excel
