### ISSUE TITLE
商品排序

### ISSUE THREAD

**Issue by brain502** [brain502/Getmii#7]
拖曳時，無法往上滑動頁面，只能往下滑動頁面
![default](https://user-images.githubusercontent.com/32536714/42835625-ccdb6aa2-8a2b-11e8-9a3c-b6cf725684e4.jpg)
@hungmi

**Comment by hungmi** [comment]
產品清單長度超過螢幕高度，往下瀏覽時，無法將下方商品拉到螢幕上方

**Comment by chagn** [comment]
看起來是javascript的bug 先修看看, 不行再嘗試換套件
