### ISSUE TITLE
確認買家首購紅利點數

### ISSUE THREAD

**Issue by brain502** [brain502/Getmii#9]
Brain's 描述：
以前網站封測時沒問題，但是不知道為何現在這個機制不見了 => 「完成首次購物，贈送紅利點數5000點」

@hungmi

**Comment by chagn** [comment]
@brain502 這個機制是哪個時間點觸發的？當訂單變成已付款之後嗎？

**Comment by chagn** [comment]
@hungmi 
# FIXME 這個會造成不用刷卡成功就可以獲得紅利點數
https://github.com/brain502/Getmii/commit/e8a7bfd65b75965b453b353eb364930c6d5170e6

這個部分你有印象嗎？會跟這個問題有關嗎？

**Comment by hungmi** [comment]
那個備註是我修之前修購物流程問題的時候發現問題時寫下來的。我也還不清楚原因呢
狀況是只要下單後到刷卡，不用刷卡直接按瀏覽器的返回，就可以一直來回獲得紅利點數喔，這不是首購的紅利點數，是每次訂單的獎勵。

**Comment by brain502** [comment]
@chagn  已回覆如上

**Comment by chagn** [comment]
@brain502 

我應該找到bug了，然後也查過資料庫，過去從來沒有成功觸發過首購送點。
不過修改前跟你確認一下邏輯。

每次結帳總金額 x 0.1 為贈送的紅利點數，這個規則在首購也會觸發嗎？
意思是說假設首購訂單總金額為1,000
該消費者會得到 1,000 x 0.1 + 5,000 = 5,100 的紅利點數？

**Comment by brain502** [comment]
@chagn 
該消費者會得到 1,000 x 0.1 + 5,000 = 5,100 的紅利點數？
=> Yes

**Comment by chagn** [comment]
https://github.com/brain502/Getmii/pull/22

已修正。

**Comment by brain502** [comment]
@chagn 補充

測試時間： 11/29 20:28
正式站一樣的手法 (參閱 Github #9，最後一個留言)

結果：
1. 第三方綠界頁面，出現交易失敗
2. 會員，我的訂單，有出現訂單編號 8B291H4000118

**Comment by brain502** [comment]
Checked OK
